### ISSUE TITLE
Does not support PHP5.6?

### ISSUE THREAD

**Issue by mojie126** [DenzoNL/riplogchecker#18]
Does not support PHP5.6?

**Comment by DenzoNL** [comment]
Nope, see the ```composer.json```. Although not many PHP 7.0.0 features are used, so it should be relatively easy to port. However, ideally you don't want to be using 5.6 anymore.

**Comment by mojie126** [comment]
Yes, so I didn't use composer install. I changed the source code directly and loaded it, but thank you for your reply

**Comment by DenzoNL** [comment]
If you delete the return type declarations, that is probably 99% of the PHP7 features used, let me know if you need any help with it :)

**Comment by mojie126** [comment]
Yes, that's what I did. PHP7 is becoming more and more like Java
If I can be compatible with PHP5.6, I think it might be better, after all, composer install is easier to use
