### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by inverse** [DenzoNL/riplogchecker#4]
Would be great if you could setup some CI like travis on this project. Let me know if you need a hand.

**Comment by DenzoNL** [comment]
Good idea! I actually wanted to implement this already, but I didn't have the time yet. I'd also like to implement StyleCI if possible, but I don't have any experience with it so far.

EDIT: I've set it up the basics of it, but I'm not that familiar with it. If you have any tips, let me know in an issue or pull request :)

**Comment by inverse** [comment]
Super :+1:
